apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "example-pv"
spec:
  capacity:
    storage: "5Gi"
  accessModes:
    - "ReadWriteOnce"
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: "/srv/nfs/example-pv"
    server: "fqdn.server.example.com"
